### ISSUE TITLE
one for all or all for one

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#110]
I want to raise the question of whether `kamal` should be able to handle multiple regions simultaneously or if we should treat it as a deployment per region.

The single deployment per region can probably keep things simple since there is no need to figure out where should this request go to or which region should update its graph based on this diff file.
The problem with this is that we would need to figure out how to do the routing on the transport layer ourselves. i.e. url parameters, app name. 
Another problem is that Java is quite memory hungry, and having an deployment per region would mean that we might use quite some memory just to keep it going

The multi-region deployment makes things easier for the frontend, since a single backend would be responsible for the routing. It also saves memory since all the regions use the same underlying JVM.
However it makes the maintenance of the app itself much more complicated :(

I am personally more inclined to a multi-region deployment since I guess that managing those things in code should not be that much of a problem.

What do you think?

**Comment by mehdisadeghi** [comment]
I think for the beginning a multi-region approach makes sense. There are many tools such as load balancers that can route traffic to different servers. We can always increase the number of request handling instances as the incoming traffic grows.  

For this problem we can (and must) leverage the cloud provider's tools. Most of them offer us to choose a region for instances. I think they also provide some traffic routing features (I have not used them, but I think they should exist!). Of course then we can think whether those regional instances really need to load everything or only a part of datasets? In that case then we have to come up with a solution to distinguish between servers that have our data or they don't. This will make even the single deployment per region approach complicated, because regional users might want to look up other regions' information. 

Now that you brought up this problem, I remembered that the Öffi app, asks users upfront to choose a region and then it will be limited only to that region. Users can change regions of course.

**Comment by carocad** [comment]
the latest version of master has this included. Several osm/gtfs pairs can be defined in the config file which will then be read into memory. See #127
