### ISSUE TITLE
Automate adding OSM files to Cloud Storage

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/kamal#50]
At the moment we have to download files from Overpass API or geofabrik website and then manually upload them to Firebase which is a tedious task.

Let's automate this!

**Comment by carocad** [comment]
kamal can now download files automatically through overpass api.

I dont think that we need this anymore since the output of the preprocessing stage is what we care about and that change very slowly so we can live with updating it once in a month or so

Closing this for now. Feel free to reopen if you think this is a must have for the time being
