### ISSUE TITLE
auto-deploy on github tag

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#73]
It would be nice if travis-ci would auto-deploy our code to Clojars whenever a tag is added to the master branch i.e. release tag

**Comment by mehdisadeghi** [comment]
@carocad I did some research on this and it is possible to some extend but not completely. 

Travis can deploy artifacts to clojars.org. But here is the catch, it has no idea about the tags. Unless we manually write some scripts to handle deployment, it will not take them into account. But do we really need to automate (major) releases which will happen once in a while?

Another solution which is pretty common is using SNAPSHOTs. We can continuously deploy snapshots of master branch to clojars using travis. Snapshots don't need explicit versioning, since clojars will internally tag them by time of upload and will always return the latest one. 

Now back to the tags. Leiningen can automate creating non-snapshot releases and tags. It can also increase versions. But this part is manual and travis can't do it, specially when it comes to signing releases (not snapshots).

There might be of course some exotic ways to automate all this using travis but it wouldn't worth the effort and complexity IMO.

**Comment by carocad** [comment]
@mehdisadeghi awesome ! nice work on this research that you did.

As you said, this is more a nice to have. In my mind the point here is that the process for publishing is the same for every repo so there isnt really a reason not to standardise. 

I think your changes are already pretty good. According to [this link] (https://docs.travis-ci.com/user/deployment/releases/) it is possible to deploy on `tags`.

For me this is not a priority right now since we dont have that many repos nor deployments. If you think that you have nailed it then please go ahead and make the PR. I would be more than happy to have such an addition :)

**Comment by mehdisadeghi** [comment]
@carocad let me create some prs! I had seen that travis article but my brain was locken in the though that we want to use Github GUI to trigger a build by creating a tag! Anyway, we have to try and find out how it works...

**Comment by mehdisadeghi** [comment]
Done in #74
